name: Endpoint tests
run-name: ${{ github.actor }} automated testing ğŸ› ï¸

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    - name: build required docker images
      run: bash build.sh
    - name: run docker compose
      run: docker compose -f ./compose/compose.test.yaml up --abort-on-container-exit